apiVersion: v1
kind: Service
metadata:
  labels:
    app: hcl-deployment
  name: hcl-service    
spec:
  ports:
    - nodePort: 32128
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: hcl-deployment
  type: LoadBalancer 
